name: Generate Swift Client

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install OpenAPI Generator CLI
      run: npm install @openapitools/openapi-generator-cli -g

    - name: Generate Swift Client
      run: openapi-generator-cli generate -i openapi.yaml -g swift5 -o /tmp/swift-client --skip-validate-spec

    - name: Checkout Target Repository
      uses: actions/checkout@v2
      with:
        repository: 'kosztid/PowderTrackrAPI'
        token: ${{ secrets.TARGET_REPO_TOKEN }}
        path: 'target-repo'

    - name: Copy Generated Code to Target Repository
      run: |
        cp -r /tmp/swift-client/* target-repo/

    - name: Commit and Push
      run: |
        cd target-repo
        git config --local user.email "koszti.dominik@gmail.com"
        git config --local user.name "kosztid"
        git add .
        git commit -m "Update generated Swift client"
        git push